### ISSUE TITLE
ToDo Liste

### ISSUE THREAD

**Issue by CeroProgramming** [Info-ag/labplaner#12]
Flask/Backend:
- [ ] API Key Verifizierung
- [ ] API Key Generierung

Database:
- [ ] Tabellen für One to Many Relationships (z.B. AG IDs)
- [ ] Optimieren von Stringlängen
- [ ] Support für Zeitdaten verbessern

Frontend:
- [ ] 

Algorithm:
- [ ]

**Comment by jnsdrtlf** [comment]
Würde vorschlagen, die einzelnen Punkte in extra issues einzutragen. Dann kann man das jeweils assignen und labels hinzufügen

**Comment by jnsdrtlf** [comment]
habe bereits weitere issues erstellt. Issue erstmal geschlossen
